swagger: '2.0'
info:
  version: '1'
  title: テスト
  contact:
    email: dummy@dummy.com
host: dummy
basePath: /test
schemes:
  - https
paths:
  /test:
    get:
      summary: テスト
      description: テスト用
      operationId: test
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - in: query
          name: q
          description: キー
          required: true
          type: string
      responses:
        '200':
          description: 正常応答
          schema:
            $ref: '#/definitions/OK'
        default:
          description: エラー応答
          schema:
            $ref: '#/definitions/NG'
definitions:
  OK:
    type: object
    properties:
      msg:
        type: string
        example: OK
  NG:
    type: object
    properties:
      msg:
        type: string
        example: NG
